spring:
  jpa:
    generate-ddl: 'true'
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/arenadb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher