spring:
  jpa:
    generate-ddl: 'true'
    database: mysql
    properties:
      hibernate:
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    password: rkdghk1!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/arenadb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      suffix: .jsp
#      static-path-pattern: /static/** # spring mvc 정적경로 변경
#  thymeleaf:
#    check-template-location: true
#    prefix: classpath:/templates/   # .html 파일을 불러오기 위한 경로 설정(src/main/resources/templates)
#    suffix: .html   # 파일 확장자
#    cache: false
